[config]

# Choose the default graph style. available: bar, compact, norm, spark
usage_graph_style = "bar"

# Default display unit: 'kb', 'mb', 'gb'
default_unit = "kb"

# Default usage view : 'yesterday', 'today', 'thisweek', 'month'
# NOTE: 'month' will always be the CURRENT MONTH
default_view = "today"
